### PR TITLE
Fix export of unified core document

### LINKED ISSUE #290: Export > Core Document (one global CSV file)... Only exports last asset in list of files.
Issue found in in Windows version specifically. With a hundred files in the window, BWF MetaEdit only exports information from the last item in the list!

### PR DESCRIPTION
**Pull request by g-maxime**
Fixes #290

### CODE REVIEW

**Comment by g-maxime** [comment]
Snapshot: https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20240808-2/

**Comment by MarcosSueiro** [comment]
Hi Maxime,

Has this pull request been implemented in any builds?

Thank you

Marcos

Marcos Sueiro Bal
Archive Manager
New York Public Radio
646 829 4063
160 Varick St
New York NY 10013
USA

**Comment by g-maxime** [comment]
@MarcosSueiro In this snapshot:

> Snapshot: https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20240808-2/

**Comment by MarcosSueiro** [comment]
Thank you Maxime!

Marcos Sueiro Bal
Archive Manager
New York Public Radio
646 829 4063
160 Varick St
New York NY 10013
USA

**Comment by MarcosSueiro** [comment]
Hi sorry Maxime, I meant to ask whether the option to remove chunks has been deployed in any available build. Thank you!

Marcos

Marcos Sueiro Bal
Archive Manager
New York Public Radio
646 829 4063
160 Varick St
New York NY 10013
USA

From: Marcos Sueiro Bal
Sent: Friday, August 9, 2024 10:23 AM
To: MediaArea/BWFMetaEdit ***@***.***>
Subject: FW: [MediaArea/BWFMetaEdit] CLI: Add --remove-chunks= option to remove non-editable fields (PR #283)

Hi Maxime,

Has this pull request been implemented in any builds?

Thank you

Marcos

Marcos Sueiro Bal
Archive Manager
New York Public Radio
646 829 4063
160 Varick St
New York NY 10013
USA

**Pull request merged**
