### PR TITLE
Split CodecID and ExtCodecID into separate fields

### LINKED ISSUE #249: Incorrect Codec ID in GUI
Codec shows correctly as FFFE in the CLI, but as 0001 in the GUI... See below

A test file is [here](https://drive.google.com/file/d/1Nqcu2u40vJPKDfqOz9CGOAky7h_gVqJa/view?usp=sharing).
```
C:\mySoftware>bwfmetaedit --out-tech "W:\ARCHIVESNAS1\INGEST\01 PLEASE REVIEW\codec_and_channel_layout_questions\WQXR-YAS-1973-12-12-600083.2 Joseph Piorine_COPY.wav"
FileName,FileSize,Format,CodecID,Channels,SampleRate,BitRate,BitPerSample,Duration,UnsupportedChunks,bext,INFO,Cue,XMP,aXML,iXML,MD5Stored,MD5Generated,Errors,Information
W:\ARCHIVESNAS1\INGEST\01 PLEASE REVIEW\codec_and_channel_layout_questions\WQXR-YAS-1973-12-12-600083.2 Joseph Piorine_COPY.wav,1469153918,Wave,FFFE,1,96000,2304000,24,01:25:01.206,,Version 1,Yes,No,Yes,No,No,EC2DA8B77618AB07996663AAADEE7388,,,
```
WrongCodecIDInBWFMEGUI

### PR DESCRIPTION
**Pull request by g-maxime**
Fixes #249

### CODE REVIEW

**Comment by MarcosSueiro** [comment]
Thank you!! :-)

**Comment by JeromeMartinez** [comment]
@MarcosSueiro I think that I prefer to do as in MediaInfo, i.e. having only one field, which has the 2CC CodecID when it is not 0xFFFE, else the GUID from the [WAVEFORMATEXTENSIBLE ](https://learn.microsoft.com/en-us/windows/win32/api/mmreg/ns-mmreg-waveformatextensible), e.g. `00000001-0000-0010-8000-00AA00389B71`.
In both CLI and GUI.
0xFFFE would be "hidden", but easy to recognize (GUID instead of 2CC in the CodecID field).
Is it fine for you?

**Comment by MarcosSueiro** [comment]
@JeromeMartinez, in MediaInfo, I get 

  `<CodecID>00000001-0000-0010-8000-00AA00389B71</CodecID>` for a 0xFFFE file

and 

`<CodecID>1</CodecID>` for a 0x0001 file.

Having a consistent, similar display in one field of BWFME in both CLI and GUI would be better. 

I only wonder if others may find the numerical coding not so helpful in terms of finding documentation about the Codec.

As a comparison, exiftool shows

`<RIFF:Encoding>Extensible</RIFF:Encoding>` for a 0xFFFE file

and 

`<RIFF:Encoding>Microsoft PCM</RIFF:Encoding>` for a 0x0001 file.

We do not have a strong preference as long as GUI and CLI are consistent.

Thank you!

**Comment by JeromeMartinez** [comment]
> `<RIFF:Encoding>Extensible</RIFF:Encoding>` for a 0xFFFE file

Well, it is not enough, because if you have only that you don't have the real CodecID (the "extended" one), a file with 0xFFFE may also be "Microsoft PCM" (`0000XXXX-0000-0010-8000-00AA00389B71` is for legacy mapping, so corresponds to `XXXX`, `XXXX` being `0001` in both, in the case of "Microsoft PCM")
In practice, any long CodecID means "Extensible" in ExifTools.

> Having a consistent, similar display in one field of BWFME in both CLI and GUI would be better.

@g-maxime, please adapt the PR for one field only, and full GUID (it is not so much used but in theory any byte of the GUID can be different).

**Comment by JeromeMartinez** [comment]
@MarcosSueiro you can check [the latest development snapshot](https://mediaarea.net/download/snapshots/binary/).

**Pull request merged**
