### PR TITLE
Add option to export all metadata into one xml

### LINKED ISSUE #51: Q/FR: Getting iXML from CLI
Hi,

Currently from CLI, I can only see a function to export iXML of a wav to a new file, but no way to just return this iXML as a string.

Do I miss anything ?
Could it be added for the future ? 😃 

Thx !

### LINKED ISSUE #196: Allow complete export of all chunks under one master xml: Core, Tech, Cue

### LINKED ISSUE #238: support method to report xml to stdout
Currently `bwfmetaedit --out-core-xml file.wav` writes a sidecar file. `bwfmetaedit --out-core-xml=file.xml file.wav` writes to a specified file, but there's no way to get the xml without a temp file. Could we support `--out-core-xml=-` or something similar when wishing to avoid a temp file.

### PR DESCRIPTION
**Pull request by g-maxime**
Signed-off-by: Maxime Gervais <gervais.maxime@gmail.com>

Fixes #196, Fixes #51, Fixes #238

### CODE REVIEW

**Review by JeromeMartinez — CHANGES_REQUESTED** [review]
Remove the spaces with iXML/etc, so one day we could import "as is" the block (so keep extra carriage returns etc as is too) and have full reversibility to source iXML.

```
        <iXML>
<a></a>        </iXML>
```
--> 

```
        <iXML><a></a></iXML>
```

and

```
        <iXML><![CDATA[<?xml?>
<a></a>c
]]>        </iXML>
```
--> 

```
        <iXML><![CDATA[<?xml?>
<a></a>c
]]></iXML>
```

***

Add `--out-iXML=`/etc so we have a more coherent list of options

***

In GUI, put the new option at the top, and add a menu separator.

**Comment by JeromeMartinez** [comment]
> --out-iXML= Is absent because in case of multiple file, the output will be invalid, except if we wrap it into an other xml?

We could reject the option if more than 1 file.

**Comment by MarcosSueiro** [comment]
...or make it part of the tech output, somewhat mimicking the GUI? Same could be done for all other xml chunks...

**Comment by JeromeMartinez** [comment]
> ...or make it part of the tech output, somewhat mimicking the GUI? Same could be done for all other xml chunks...

@MarcosSueiro this part is already implemented, but outside of the "tech" part (you have "core", "tech", "ixml", etc...)
You can test [this build](https://mediaarea.net/download/snapshots/binary/bwfmetaedit/20221110-3/) with ` --out-xml` and ` --out-xml=` (put a file name after `=`).

**Comment by MarcosSueiro** [comment]
@JeromeMartinez and @g-maxime the new `--out-xml` output looks fantastic! Is it OK that XMP includes the xml declaration? (`<?xml version="1.0" encoding="ASCII"?>`)

I think it would be very useful to include error/warning reports (and their settings in rules/File management/MD5), do you think this is possible?

**Comment by JeromeMartinez** [comment]
> Is it OK that XMP includes the xml declaration? 

@MarcosSueiro I don't get it, I tested with `<?xml version="1.0" encoding="ASCII"?><a></a>` and it is as I expect, XMP element with XMP data.

***

@g-maxime I tested with `<?xml version="1.0" encoding="cp437"?><a></a>` and it is not in CDATA, but this encoding is incompatible with UTF-8, I think it is safer to put CDATA if encoding is not UTF-8 or ASCII.
BTW, change request: instead of deleting the xml declaration, replace by comment `<!--<?xml version="1.0" encoding="ASCII"?>-->` so we keep the information (version, encoding, presence of the declaration) for potential revert.

**Comment by MarcosSueiro** [comment]
> > Is it OK that XMP includes the xml declaration?
> 
> @MarcosSueiro I don't get it, I tested with `<?xml version="1.0" encoding="ASCII"?><a></a>` and it is as I expect, XMP element with XMP data.
> 
> @g-maxime I tested with `<?xml version="1.0" encoding="cp437"?><a></a>` and it is not in CDATA, but this encoding is incompatible with UTF-8, I think it is safer to put CDATA if encoding is not UTF-8 or ASCII. BTW, change request: instead of deleting the xml declaration, replace by comment `<!--<?xml version="1.0" encoding="ASCII"?>-->` so we keep the information (version, encoding, presence of the declaration) for potential revert.

I like that solution @g-maxime . 
@JeromeMartinez this is what I get:

```
<XMP><?xml version="1.0" encoding="ASCII"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/"
           x:xmptk="Adobe XMP Core 5.6-c148 79.163765, 2019/01/24-18:11:46        ">
   <rdf:Description xmlns:et="http://ns.exiftool.ca/1.0/"
                    xmlns:ExifTool="http://ns.exiftool.ca/ExifTool/1.0/"
                    xmlns:System="http://ns.exiftool.ca/File/System/1.0/"
                    xmlns:File="http://ns.exiftool.ca/File/1.0/"
                    xmlns:XMP-x="http://ns.exiftool.ca/XMP/XMP-x/1.0/"
                    xmlns:XMP-xmp="http://ns.exiftool.ca/XMP/XMP-xmp/1.0/"
                    xmlns:XMP-xmpMM="http://ns.exiftool.ca/XMP/XMP-xmpMM/1.0/"
                    xmlns:XMP-xmpDM="http://ns.exiftool.ca/XMP/XMP-xmpDM/1.0/"
                    xmlns:XMP-dc="http://ns.exiftool.ca/XMP/XMP-dc/1.0/"
                    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
      <ExifTool:ExifToolVersion>11.69</ExifTool:ExifToolVersion>
      <System:FileName>WNYC-URBN-1997-01-11-52369.2 State State Congress Stockbrokers Mutuals Livoti.wav.XMP.xml</System:FileName>
      <System:Directory>W:/ARCHIVESNAS1/INGEST/01 PLEASE REVIEW/Levy/GeorgeBloodShipments/_6-Ready-for-Ingest/URBNReels20210603/data</System:Directory>
      <System:FileSize>6.3 kB</System:FileSize>
...
```

**Comment by MarcosSueiro** [comment]
Actually the enclosed (and cc:ed below) checks out as well-formed xml so no need to enclose XMP in CDATA, we can use xpacket instead. I thnik this will be much more usable than using CDATA.

```
<?xml version="1.0" encoding="UTF-8"?>
<conformance_point_document>
   <File
      name="W:\ARCHIVESNAS1\INGEST\01 PLEASE REVIEW\On the Media\WNYC-OTM-1996-01-07-9297.5 Govt shutdown.WAV">
      <Technical>
         <FileSize>294213864</FileSize>
         <Format>Wave</Format>
         <CodecID>0001</CodecID>
         <Channels>1</Channels>
         <SampleRate>48000</SampleRate>
         <BitRate>768000</BitRate>
         <BitPerSample>16</BitPerSample>
         <Duration>00:51:04.575</Duration>
         <UnsupportedChunks>DISP</UnsupportedChunks>
         <bext>Version 1</bext>
         <INFO>Yes</INFO>
         <Cue>Yes</Cue>
         <XMP>Yes</XMP>
         <aXML>No</aXML>
         <iXML>Yes</iXML>
         <MD5Stored>9F507CBB439972BAD550E48997DE778E</MD5Stored>
         <Information> </Information>
      </Technical>
      <Core>
         <Description>WNYC-OTM-1996-01-07-9297.5 Govt shutdown</Description>
         <Originator>MARCOS</Originator>
         <OriginationDate>1996-01-07</OriginationDate>
         <OriginationTime>00:00:00</OriginationTime>
         <TimeReference_translated>00:00:00.000</TimeReference_translated>
         <TimeReference>0</TimeReference>
         <BextVersion>1</BextVersion>
         <CodingHistory>This is an edited version of the preservation master file. No WNYC news</CodingHistory>
         <IARL>US, WNYC
</IARL>
         <IART>http://id.loc.gov/authorities/names/n88127931 ; http://id.loc.gov/authorities/names/n95014718 ; http://id.loc.gov/authorities/names/n96090769 ; http://id.loc.gov/authorities/names/n80071150 ; http://id.loc.gov/authorities/names/no2016044332 ; http://id.loc.gov/authorities/names/no2016012784
</IART>
         <ICMS>http://id.loc.gov/authorities/names/n90707834 ; http://id.loc.gov/authorities/names/n81047053
</ICMS>
         <ICMT>For additional details see https://cavafy.wnyc.org/assets/45c52147-b65c-4e2a-a588-5baacf826218</ICMT>
         <ICOP>Terms of Use and Reproduction: WNYC (Radio station : New York, N.Y.) Additional copyright may apply to musical selections.</ICOP>
         <ICRD>1996-01-07
</ICRD>
         <IENG>Unknown engineer ;
</IENG>
         <IGNR>Newsmagazine 
</IGNR>
         <IKEY>http://id.loc.gov/authorities/subjects/sh85070736 ; http://id.loc.gov/authorities/subjects/sh91005374 ; http://id.loc.gov/authorities/subjects/sh00003974 ; http://id.loc.gov/authorities/subjects/sh2018001795 ; http://id.loc.gov/authorities/subjects/sh2002007884 ; http://id.loc.gov/authorities/subjects/sh85002541 ; http://id.loc.gov/authorities/subjects/sh85139798 ; http://id.loc.gov/authorities/subjects/sh2002006203 ; http://id.loc.gov/authorities/subjects/sh85017603
</IKEY>
         <IMED>audio cassette
</IMED>
         <INAM>The 1996 Government shutdown
</INAM>
         <IPRD>On the Media 
</IPRD>
         <ISBJ>Host Alex S. Jones discusses, in the wake of the longest government shutdown, the coverage of budget negotiations with Robert Kuttner, Alissa Rubin, and Karen Tumulty.
</ISBJ>
         <ISFT>Adobe Audition CC (Windows) 
</ISFT>
         <ISRC>https://cavafy.wnyc.org/assets/45c52147-b65c-4e2a-a588-5baacf826218
</ISRC>
         <ISRF>WNYC audio cassette Copy: Access from 9297.
</ISRF>
         <ITCH>MARCOS 
</ITCH>
      </Core>
      <XMP>
         <?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
         <x:xmpmeta xmlns:x="adobe:ns:meta/"
            x:xmptk="Adobe XMP Core 5.5-c014 79.151805, 2013/04/09-12:08:21        ">
            <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
               <rdf:Description rdf:about="" xmlns:xmp="http://ns.adobe.com/xap/1.0/"
                  xmlns:dc="http://purl.org/dc/elements/1.1/"
                  xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
                  xmlns:stEvt="http://ns.adobe.com/xap/1.0/sType/ResourceEvent#"
                  xmlns:stRef="http://ns.adobe.com/xap/1.0/sType/ResourceRef#"
                  xmlns:xmpDM="http://ns.adobe.com/xmp/1.0/DynamicMedia/">
                  <xmp:CreatorTool>Adobe Audition CC (Windows)&#xD;&#xA;</xmp:CreatorTool>
                  <xmp:CreateDate>1996-01-07&#xD;&#xA;</xmp:CreateDate>
                  <xmp:MetadataDate>2019-01-25T15:10:42-05:00</xmp:MetadataDate>
                  <xmp:ModifyDate>2019-01-23T10:12:39-05:00</xmp:ModifyDate>
                  <dc:creator>
                     <rdf:Seq>
                        <rdf:li>http://id.loc.gov/authorities/names/n88127931</rdf:li>
                        <rdf:li>http://id.loc.gov/authorities/names/n95014718</rdf:li>
                        <rdf:li>http://id.loc.gov/authorities/names/n96090769</rdf:li>
                        <rdf:li>http://id.loc.gov/authorities/names/n80071150</rdf:li>
                        <rdf:li>http://id.loc.gov/authorities/names/no2016044332</rdf:li>
                        <rdf:li>http://id.loc.gov/authorities/names/no2016012784</rdf:li>
                     </rdf:Seq>
                  </dc:creator>
                  <dc:description>
                     <rdf:Alt>
                        <rdf:li xml:lang="x-default"
                           >Host Alex S. Jones discusses, in the wake of the longest government shutdown, the coverage of budget negotiations with Robert Kuttner, Alissa Rubin, and Karen Tumulty.&#xD;&#xA;</rdf:li>
                     </rdf:Alt>
                  </dc:description>
                  <dc:format>audio/x-wav</dc:format>
                  <dc:subject>
                     <rdf:Bag>
                        <rdf:li>http://id.loc.gov/authorities/subjects/sh2002007884</rdf:li>
                        <rdf:li>http://id.loc.gov/authorities/subjects/sh85017603</rdf:li>
                        <rdf:li>http://id.loc.gov/authorities/subjects/sh2002006203</rdf:li>
                        <rdf:li>http://id.loc.gov/authorities/subjects/sh85081863</rdf:li>
                        <rdf:li>http://id.loc.gov/authorities/subjects/sh85139798</rdf:li>
                     </rdf:Bag>
                  </dc:subject>
                  <dc:rights>
                     <rdf:Alt>
                        <rdf:li xml:lang="x-default"
                           >Terms of Use and Reproduction: WNYC (Radio station : New York, N.Y.)&#xD;&#xA;Additional copyright may apply to musical selections.&#xD;&#xA;</rdf:li>
                     </rdf:Alt>
                  </dc:rights>
                  <dc:source>audio cassette&#xD;&#xA;</dc:source>
                  <dc:type>
                     <rdf:Bag>
                        <rdf:li>Edited copy of original two-hour show.</rdf:li>
                     </rdf:Bag>
                  </dc:type>
                  <dc:title>
                     <rdf:Alt>
                        <rdf:li xml:lang="x-default"
                           >Reporting on AIDS (hour 1); "Balanced" Budget Coverage (hour 2)&#xD;&#xA;</rdf:li>
                     </rdf:Alt>
                  </dc:title>
                  <xmpMM:InstanceID>xmp.iid:a4e4587c-9ef3-a449-82d6-a5e6814c587c</xmpMM:InstanceID>
                  <xmpMM:DocumentID>xmp.did:691db1e9-5b61-d14d-a69e-609ea97c5df7</xmpMM:DocumentID>
                  <xmpMM:OriginalDocumentID>xmp.did:ec789ae2-8891-044b-9bee-643cd50ef54b</xmpMM:OriginalDocumentID>
                  <xmpMM:History>
                     <rdf:Seq>
                        <rdf:li rdf:parseType="Resource">
                           <stEvt:action>saved</stEvt:action>
                           <stEvt:instanceID>xmp.iid:ec789ae2-8891-044b-9bee-643cd50ef54b</stEvt:instanceID>
                           <stEvt:when>2019-01-22T12:12:16-05:00</stEvt:when>
                           <stEvt:softwareAgent>Adobe Audition CC (Windows)</stEvt:softwareAgent>
                           <stEvt:changed>/metadata</stEvt:changed>
                        </rdf:li>
                        <rdf:li rdf:parseType="Resource">
                           <stEvt:action>saved</stEvt:action>
                           <stEvt:instanceID>xmp.iid:7ed62f9a-deb8-c549-93aa-357146d31fce</stEvt:instanceID>
                           <stEvt:when>2019-01-23T10:12:39-05:00</stEvt:when>
                           <stEvt:softwareAgent>Adobe Audition CC 2017.1 (Windows)</stEvt:softwareAgent>
                           <stEvt:changed>/metadata</stEvt:changed>
                        </rdf:li>
                        <rdf:li rdf:parseType="Resource">
                           <stEvt:action>saved</stEvt:action>
                           <stEvt:instanceID>xmp.iid:691db1e9-5b61-d14d-a69e-609ea97c5df7</stEvt:instanceID>
                           <stEvt:when>2019-01-23T10:12:39-05:00</stEvt:when>
                           <stEvt:softwareAgent>Adobe Audition CC 2017.1 (Windows)</stEvt:softwareAgent>
                           <stEvt:changed>/</stEvt:changed>
                        </rdf:li>
                        <rdf:li rdf:parseType="Resource">
                           <stEvt:action>saved</stEvt:action>
                           <stEvt:instanceID>xmp.iid:5c080f2d-fe0e-9d44-898f-6040c5d4f095</stEvt:instanceID>
                           <stEvt:when>2019-01-24T13:36:48-05:00</stEvt:when>
                           <stEvt:softwareAgent>Adobe Audition CC (Windows)</stEvt:softwareAgent>
                           <stEvt:changed>/metadata</stEvt:changed>
                        </rdf:li>
                        <rdf:li rdf:parseType="Resource">
                           <stEvt:action>saved</stEvt:action>
                           <stEvt:instanceID>xmp.iid:a4e4587c-9ef3-a449-82d6-a5e6814c587c</stEvt:instanceID>
                           <stEvt:when>2019-01-25T15:10:42-05:00</stEvt:when>
                           <stEvt:softwareAgent>Adobe Audition CC (Windows)</stEvt:softwareAgent>
                           <stEvt:changed>/metadata</stEvt:changed>
                        </rdf:li>
                     </rdf:Seq>
                  </xmpMM:History>
                  <xmpMM:DerivedFrom rdf:parseType="Resource">
                     <stRef:instanceID>xmp.iid:7ed62f9a-deb8-c549-93aa-357146d31fce</stRef:instanceID>
                     <stRef:documentID>xmp.did:ec789ae2-8891-044b-9bee-643cd50ef54b</stRef:documentID>
                     <stRef:originalDocumentID>xmp.did:ec789ae2-8891-044b-9bee-643cd50ef54b</stRef:originalDocumentID>
                  </xmpMM:DerivedFrom>
                  <xmpDM:artist>http://id.loc.gov/authorities/names/n80071150 ; http://id.loc.gov/authorities/names/no2016044332 ; http://id.loc.gov/authorities/names/no2016012784</xmpDM:artist>
                  <xmpDM:logComment>For additional details see https://cavafy.wnyc.org/assets/45c52147-b65c-4e2a-a588-5baacf826218</xmpDM:logComment>
                  <xmpDM:engineer>Unknown engineer&#xD;&#xA;</xmpDM:engineer>
                  <xmpDM:genre>Newsmagazine&#xD;&#xA;</xmpDM:genre>
                  <xmpDM:Tracks>
                     <rdf:Bag>
                        <rdf:li rdf:parseType="Resource">
                           <xmpDM:trackName>CuePoint Markers</xmpDM:trackName>
                           <xmpDM:trackType>Cue</xmpDM:trackType>
                           <xmpDM:frameRate>f96000</xmpDM:frameRate>
                           <xmpDM:markers>
                              <rdf:Seq>
                                 <rdf:li rdf:parseType="Resource">
                                    <xmpDM:startTime>17377362f48000</xmpDM:startTime>
                                    <xmpDM:duration>2898619f48000</xmpDM:duration>
                                    <xmpDM:name>WNYC-OTM-1996-01-07-9297.5 Rubin shutdown ACLIP</xmpDM:name>
                                 </rdf:li>
                                 <rdf:li rdf:parseType="Resource">
                                    <xmpDM:startTime>147099640f48000</xmpDM:startTime>
                                    <xmpDM:name>end hour</xmpDM:name>
                                 </rdf:li>
                              </rdf:Seq>
                           </xmpDM:markers>
                        </rdf:li>
                        <rdf:li rdf:parseType="Resource">
                           <xmpDM:trackName>CD Track Markers</xmpDM:trackName>
                           <xmpDM:trackType>Track</xmpDM:trackType>
                           <xmpDM:frameRate>f96000</xmpDM:frameRate>
                        </rdf:li>
                        <rdf:li rdf:parseType="Resource">
                           <xmpDM:trackName>Subclip Markers</xmpDM:trackName>
                           <xmpDM:trackType>InOut</xmpDM:trackType>
                           <xmpDM:frameRate>f96000</xmpDM:frameRate>
                        </rdf:li>
                     </rdf:Bag>
                  </xmpDM:Tracks>
               </rdf:Description>
            </rdf:RDF>
         </x:xmpmeta>





















         <?xpacket end="w"?>
      </XMP>
      <iXML>
         <BWFXML>
            <SPEED>
               <TIMESTAMP_SAMPLES_SINCE_MIDNIGHT_LO>1684333</TIMESTAMP_SAMPLES_SINCE_MIDNIGHT_LO>
               <TIMESTAMP_SAMPLES_SINCE_MIDNIGHT_HI>0</TIMESTAMP_SAMPLES_SINCE_MIDNIGHT_HI>
            </SPEED>
            <BEXT>
               <BWF_ORIGINATION_DATE>2019-01-22</BWF_ORIGINATION_DATE>
               <BWF_ORIGINATION_TIME>09:28:14</BWF_ORIGINATION_TIME>
               <BWF_TIME_REFERENCE_LOW>1684333</BWF_TIME_REFERENCE_LOW>
               <BWF_TIME_REFERENCE_HIGH>0</BWF_TIME_REFERENCE_HIGH>
               <BWF_VERSION>1</BWF_VERSION>
               <BWF_CODING_HISTORY>No WNYC news</BWF_CODING_HISTORY>
            </BEXT>
         </BWFXML>
      </iXML>
      <Cues>
         <Cue>
            <ID>1</ID>
            <Position>17377362</Position>
            <DataChunkID>0x64617461</DataChunkID>
            <ChunkStart>0</ChunkStart>
            <BlockStart>0</BlockStart>
            <SampleOffset>17377362</SampleOffset>
            <Label>WNYC-OTM-1996-01-07-9297.5 Rubin shutdown ACLIP</Label>
            <Note/>
            <LabeledText>
               <SampleLength>2898619</SampleLength>
               <PurposeID>0x72676E20</PurposeID>
               <Country>0</Country>
               <Language>0</Language>
               <Dialect>0</Dialect>
               <CodePage>0</CodePage>
               <Text/>
            </LabeledText>
         </Cue>
         <Cue>
            <ID>2</ID>
            <Position>147099640</Position>
            <DataChunkID>0x64617461</DataChunkID>
            <ChunkStart>0</ChunkStart>
            <BlockStart>0</BlockStart>
            <SampleOffset>147099640</SampleOffset>
            <Label>end hour</Label>
            <Note/>
            <LabeledText>
               <SampleLength>0</SampleLength>
               <PurposeID>0x72676E20</PurposeID>
               <Country>0</Country>
               <Language>0</Language>
               <Dialect>0</Dialect>
               <CodePage>0</CodePage>
               <Text/>
            </LabeledText>
         </Cue>
      </Cues>
   </File>
</conformance_point_document>

```


[bwfme_markerTests.zip](https://github.com/MediaArea/BWFMetaEdit/files/9995756/bwfme_markerTests.zip)

**Comment by JeromeMartinez** [comment]
> Actually the enclosed (and cc:ed below) checks out as well-formed xml so no need to enclose XMP in CDATA, we can use xpacket instead. I thnik this will be much more usable than using CDATA.

CDATA is for when it is malformed.
[XMLDecl is optional](https://www.w3.org/TR/xml/#NT-prolog) so XML without it should be handled, e.g. as XML 1.0 UTF-8, @g-Maxime please modify the PR accordingly.

**Comment by g-maxime** [comment]
Normally, the current code only puts invalid XML into CDATA, I will check for bugs.

I will update the PR soon to comment out instead of delete xml declaration, or use CDATA if the declared encoding isn't utf-8.

Is the xpacket tag part of the original XML?

**Comment by g-maxime** [comment]
New [snapshot](https://mediaarea.net/download/snapshots/binary/bwfmetaedit/20221113/)

**Comment by MarcosSueiro** [comment]
@g-maxime , looks like xpacket is part of the original Adobe Audition XMP: https://forums.cockos.com/showthread.php?t=171434

**Review by JeromeMartinez — APPROVED** [review]

**Comment by JeromeMartinez** [comment]
@MarcosSueiro @dericed please test [latest snapshot](https://mediaarea.net/download/snapshots/binary/).

**Comment by MarcosSueiro** [comment]
Looks good but I think `rdf:Description` needs an `@rdf:about` with full filepath in order to be valid RDF.

**Comment by MarcosSueiro** [comment]
Thank you also for adding `@samplerate` to Cues!!

**Comment by JeromeMartinez** [comment]
> Looks good but I think `rdf:Description` needs an `@rdf:about` with full filepath in order to be valid RDF.

I checked with XMP content from https://github.com/MediaArea/BWFMetaEdit/pull/237#issuecomment-1312039318, and I see the `@rdf:about` in output if it is in the XMP:

```
[...]
        <XMP><?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/"
  x:xmptk="Adobe XMP Core 5.5-c014 79.151805, 2013/04/09-12:08:21        ">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
     <rdf:Description rdf:about="" xmlns:xmp="http://ns.adobe.com/xap/1.0/"
[...]
```

All extra spaces and empty attributes are there, content is copied as is, no normalization.
Please provide a sample file with the issue you describe.

**Comment by MarcosSueiro** [comment]
You are right @JeromeMartinez  --I stand corrected. 

The XMP is valid RDF according to the [W3C's validator](https://www.w3.org/RDF/Validator/).

**Pull request merged**
