### PR TITLE
GUI: Repeat context menu in main menu -> edit

### PR DESCRIPTION
**Pull request by g-maxime**
Signed-off-by: Maxime Gervais <gervais.maxime@gmail.com>

### CODE REVIEW

**Comment by dericed** [comment]
This is really convenient, but the ui lags the function. For instance if I open many files and right click on an existing "Description" value, I can click "Fill all fields with this value" and then all other files appeared filled with that value and show in Green. But if I open many files and select one Description value and then select "Fill all fields with this value" from the Edit list, there's no visual ui feedback, but if i click on the other files, then they show the edited value. Somehow the ui refreshes after the right click fill option but not the Edit menu fill option.

**Comment by dericed** [comment]
ping

**Comment by dericed** [comment]
um, thanks for merging, but I left some concerns about the PR at https://github.com/MediaArea/BWFMetaEdit/pull/187#issuecomment-747122485

**Comment by JeromeMartinez** [comment]
Oops!

**Comment by ablwr** [comment]
Teehee - I'll file a new issue about this though, after I give it a review

**Comment by ablwr** [comment]
This initially seemed to be working with me, filling in all fields with the same value from the Core or File views.

However, if I try to first fill out the Description in the File view, and try to then fill all fields with that value, it causes the value to disappear from the Description that I was just editing and also doesn't populate the other fields.

**Comment by g-maxime** [comment]
@ablwr Please test [this snapshot](https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20210202/)

**Comment by ablwr** [comment]
Tested and working fine now!

**Pull request merged**
