### PR TITLE
Update resources with new logo

### PR DESCRIPTION
**Pull request by g-maxime**
Signed-off-by: Maxime Gervais <gervais.maxime@gmail.com>

### CODE REVIEW

**Comment by JeromeMartinez** [comment]
@ablwr @dericed please test [this snapshot](https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20200408-2/), about the logo.

**Comment by ablwr** [comment]
Is there a significant difference between the Ubuntu 18.04 and 18.10 builds? I'm on the former, but only the latter is available. I'm getting an issue with libqt dependencies, so I could try rebuilding. 

I'll try from source. The last few builds I haven't been able to compile from source -- my last build is the 20200404-01 snapshot.

**Comment by JeromeMartinez** [comment]
@ablwr automation failed a bit yesterday, I relaunched it so this [snapshot dir](https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20200408-3/) will be ready soon.
If you are in hurry go directly to [OBS BWF MetaEdit snapshot for Ubuntu 18.04](https://build.opensuse.org/package/binaries/home:MediaArea_net:snapshots/BWFMetaEdit/xUbuntu_18.04)

**Comment by ablwr** [comment]
working great, thanks!!

**Pull request merged**
