### PR TITLE
Cue chunks editor

### LINKED ISSUE #107: support view of cues chunk
Starting a ticket here as this issue has come up several times in discovery interviews. The "cue " chunk contains information that often has a descriptive relationship to the metadata of the bext and LIST-INFO chunk. I'm uncertain if it is in scope of BWF MetaEdit to support editing this chunk but I think it could be useful to view it in BWF MetaEdit.

### PR DESCRIPTION
**Pull request by g-maxime**
Snapshot: https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20210302/
(to be tested on **copies** of your files)

Fixes #107 

Signed-ioff-by: Maxime Gervais <gervais.maxime@gmail.com>

### CODE REVIEW

**Comment by ablwr** [comment]
Thanks @g-maxime!

The editor is looking pretty nice.

I am having an issue where if I edit one of the cues, I get this kind of error when I go to open up the cue viewer/editor a second time:

Screenshot from 2020-12-03 22-52-01

Now that I have saved this test file, I keep getting that message. It seems like it's permanently impacting the cue data.

**Comment by ablwr** [comment]
This snapshot is also freezing up quite a bit, and it even temporarily locks my entire computer and makes the fan whirl up. it happened a few times when I added a new file (once via drag'n'drop, once from adding via File...). Sorry I don't have any more error details than that!

**Comment by MarcosSueiro** [comment]
It seems all chunks and markers get a 00:00:00.000 time

Build BWF MetaEdit 20.08.20201201

image

**Comment by MarcosSueiro** [comment]
Hello, what is the CLI to export the cue chunk as an xml?

**Comment by MarcosSueiro** [comment]
Here is the WAVE file that generated the above view

https://drive.google.com/file/d/1DL5ivZsX6OPSspzrnWMeQgDD-Y-A-02k/view?usp=sharing

Marcos

**Comment by g-maxime** [comment]
> It seems all chunks and markers get a 00:00:00.000 time
> Build BWF MetaEdit 20.08.20201201
> 
> Here is the WAVE file that generated the view below
> 
> https://drive.google.com/file/d/1DL5ivZsX6OPSspzrnWMeQgDD-Y-A-02k/view?usp=sharing
> 
> Marcos
> 

BlockStart must be set only for compressed or wavl data (currently unhandled) according to my doc. I will check if there is a more recent usage (maybe for addressing point past the 4gb limit).

This file also contains an r64m chuck that is not handled by now (but it's planned)

> Hello, what is the CLI command to export the cue chunk as an xml?

./bwfmetaedit --out-cue-xml <file>

**Comment by g-maxime** [comment]
> Thanks @g-maxime!
> 
> The editor is looking pretty nice.
> 
> I am having an issue where if I edit one of the cues, I get this kind of error when I go to open up the cue viewer/editor a second time:
> 
> Screenshot from 2020-12-03 22-52-01
> 
> Now that I have saved this test file, I keep getting that message. It seems like it's permanently impacting the cue data.

I wasn't able to reproduce this bug.

Here a new snapshot with some bugs fixed :
https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20201209-2/

**Comment by JeromeMartinez** [comment]
> BlockStart must be set only for compressed or wavl data (currently unhandled) according to my doc.

[the spec](http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/Docs/riffmci.pdf) looks like to say that (to be deciphered!), but for the moment, at least in the development, we could permit non zero content as it seems a common usage.

**Comment by JeromeMartinez** [comment]
> It seems all chunks and markers get a 00:00:00.000 time

Checking this file, there is something like that in the file:
```
26193C   Cue point (24 bytes)
26193C    ID:                                  5 (0x00000005)
261940    Position:                            0 (0x00000000)
261944    DataChunkID:                         data
261948    ChunkStart:                          0 (0x00000000)
26194C    BlockStart:                          1821600 (0x001BCBA0)
261950    SampleOffset:                        910800 (0x000DE5D0)
```

Usually it is something like that:
```
1125E0C   Cue point (24 bytes)
1125E0C    ID:                                  4 (0x00000004)
1125E10    Position:                            4217879 (0x00405C17)
1125E14    DataChunkID:                         data
1125E18    ChunkStart:                          0 (0x00000000)
1125E1C    BlockStart:                          0 (0x00000000)
1125E20    SampleOffset:                        4217879 (0x00405C17)
```

spec says:
- "PositionSpecifies the sample position of the cue point"
- "SampleOffset Specifies the sample offset of the cue point relative to the start of the block"
In the case of PCM, BlockStart is expected to be 0 and Position == SampleOffset.

In this file, BlockStart == SampleOffset * SampleSize, and Position (the field used for the start display in the dev snapshot) is 0.
In my opinion it is out of specs. But if it exists in real world... What is the tool used for creating such cue?

We could support both.
Suggestion of algorithm when a cue is loaded:
- if PCM and Position == SampleOffset and DataChunkID == "data" and ChunkStart == 0 and BlockStart ==0 then standard edition
- else if Position == 0 and  DataChunkID == "data" and ChunkStart == 0 and BlockStart == SampleOffset * SampleSize then alternative non standard edition
- else not supported

We could switch between both edition methods with a radio button so users can fix (in the way they want).

@kmurmur @dericed fine for you?

**Comment by MarcosSueiro** [comment]
Thanks Jerome!

The file was created (you may have guessed it, @dericed) by [DAVID/DigaSystem](https://www.davidsystems.com/).

I enclose a new version with additional markers: https://drive.google.com/file/d/1Z0um-LyN40BOl8qdeL1kqcp_h6rrsDKk/view?usp=sharing

This file should have 13 total markers

image

but only five show up on BWF ME (perhaps related to the errors you found):

DAVIDFileW13MarkersBWFME

I would be weary of allowing users to "fix" these issues if we do not know the specs....

Thanks again!!!

**Comment by MarcosSueiro** [comment]
> --out-cue-xml

Hi, is this already implemented in Build BWF MetaEdit 20.08.20201201 ? I cannot seem to make it work.

Thanks!!

**Comment by JeromeMartinez** [comment]
@MarcosSueiro I tested with [the latest CLI version](https://mediaarea.net/download/snapshots/binary/bwfmetaedit/20201209-2/) on Linux, seems fine (sidecar XML file added; we should maybe permit another file name in the future, for all options).
Did you use the CLI version (not the GUI version)?

**Comment by JeromeMartinez** [comment]
> This file should have 13 total markers (see a few below)

The file linked has very different marker labels than your screenshot, and an hex dump of content shows only 5 markers, are you sure it is the same file between download and screenshot?

**Comment by MarcosSueiro** [comment]
Sorry Jerome, I was using a very outdated CLI –I thought it was automatically updated of you installed the GUI.

Which version do I need for x64? The zip file appears not to have an .exe

Marcos

**Comment by MarcosSueiro** [comment]
> 
> 
> > This file should have 13 total markers (see a few below)
> 
> The file linked has very different marker labels than your screenshot, and an hex dump of content shows only 5 markers, are you sure it is the same file between download and screenshot?

Sorry @JeromeMartinez , you are completely right. BWF ME is showing the correct Cue Markers. It seems that DAVID has two different types of markers, depending on which editor you use within its environment --and they do not seem to talk to each other.

- The DigaSystem database manager stores its markers (screenshot below, same as previously) only in a sidecar xml file.
- Its audio editor (EasyTrack) creates (non-conformant) Cue Markers. (It also seems to add extraneous chunks, but never mind...) 

Sorry about the confusion!!

image

**Comment by JeromeMartinez** [comment]
Development snapshot, with readout/export/edition/import/write of the cue data (both the standard format and the EasyTagEditor format, and you can switch between them): [Windows](https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20201217-2/BWFMetaEdit_GUI_20.08.20201217_Windows_x64.exe), [macOS](https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20201217-2/BWFMetaEdit_GUI_20.08.20201217_Mac.dmg), [others](https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20201217-2/).
Must be tested on **copies** of your files.

@MarcosSueiro please test.
@dericed @kmurmur please forward links to people interested in beta testing (with warning about the need to use copies of files)

@g-maxime please replace the text for the alternative format in "Use non standard DAVID DigaSystem Easy Tag Editor CUE point format".

**Comment by ablwr** [comment]
Looks like there's been some additional changes since the last development snapshot. Would it be not too inconvenient for us to get another?

I can also build from scratch, but @MarcosSueiro has done some great testing and it'd be great to get some more :sunglasses:

**Comment by g-maxime** [comment]
Latest snapshot:
- GUI: https://mediaarea.net/download/snapshots/binary/bwfmetaedit-gui/20210302/
- CLI: https://mediaarea.net/download/snapshots/binary/bwfmetaedit/20210302/

**Review by dericed — APPROVED** [review]

**Pull request merged**
